- name: Setup Python virtual environment
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600 

    - name: Install packages
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present

    - name: Create a virtual environment for Python packages
      ansible.builtin.command:
        cmd: python3 -m venv /opt/ansible-venv
        creates: /opt/ansible-venv

    - name: Install pip packages inside the virtual environment
      ansible.builtin.pip:
        name: "{{ pip_packages }}"
        state: present
        virtualenv: /opt/ansible-venv